export const FETCH_ROOT_RROPS_REQUESTED = 'FETCH_ROOT_RROPS_REQUESTED'
export type FETCH_ROOT_RROPS_REQUESTED = typeof FETCH_ROOT_RROPS_REQUESTED

export const POST_RECORD_REQUESTED = 'POST_RECORD_REQUESTED'
export type POST_RECORD_REQUESTED = typeof POST_RECORD_REQUESTED

export const PATCH_RECORD_REQUESTED = 'PATCH_RECORD_REQUESTED'
export type PATCH_RECORD_REQUESTED = typeof PATCH_RECORD_REQUESTED

export const DELETE_RECORD_REQUESTED = 'DELETE_RECORD_REQUESTED'
export type DELETE_RECORD_REQUESTED = typeof DELETE_RECORD_REQUESTED
